# Generated by Django 4.0.3 on 2023-08-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimonitor', '0002_user_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='user',
            new_name='sender',
        ),
        migrations.AddField(
            model_name='transaction',
            name='narration',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference',
            field=models.CharField(default='', max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='to',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='tier',
            field=models.CharField(choices=[('tier1', 'Tier 1'), ('tier2', 'Tier 2'), ('tier3', 'Tier 3')], default='tier1', max_length=10),
        ),
    ]
