# Generated by Django 4.0.3 on 2023-08-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimonitor', '0003_rename_timestamp_transaction_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(default='5f2157015ebe4fd5a4a5d8577854bef7', max_length=32, unique=True),
        ),
    ]
