# Generated by Django 4.0.3 on 2023-08-29 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apimonitor', '0004_alter_transaction_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_number',
            field=models.CharField(default='', editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(default='d5ae78e9c80643f9a412de555aa76c8b', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL),
        ),
    ]
