# Generated by Django 4.0.3 on 2023-08-29 07:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apimonitor', '0005_user_account_number_alter_transaction_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 29, 7, 25, 55, 224661, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(default='d527db390461467483ca023e8ad10fcc', max_length=32, unique=True),
        ),
    ]
