# Generated by Django 4.0.3 on 2023-08-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimonitor', '0007_alter_transaction_reference_alter_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='narration',
            field=models.CharField(default='Test Narration', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(default='cf5ccee95b4d41e4a321c46953943f4c', max_length=32, unique=True),
        ),
    ]
